vich_uploader:
  db_driver: orm

  mappings:
    artwork_images:
      uri_prefix: "%artwork_images%"
      upload_destination: "%kernel.project_dir%/public%artwork_images%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false

    profile_images:
      uri_prefix: "%profile_images%"
      upload_destination: "%kernel.project_dir%/public%profile_images%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      delete_on_update: false
      delete_on_remove: false
